spring.application.name=SoapJavaSB
server.port=8080
spring.main.web-application-type=servlet
#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.ws=DEBUG
spring.thymeleaf.cache=false
spring.webservices.soap.endpoint=localhost:8080/ws

##http://localhost:8080/ws/movies.wsdl